#from .login_view import my_view
from .home_view import HomeView
from .patient_home import PatientHomeView
from .select_illness_view import SelectIllnessView
from .view_available_appointments import CheckAvailableAppointmentView
from .confirm_appointment_selection_view import ConfirmAppointmentView
from .create_appointment_view import CreateAppointmentView
from .cancel_appointment_view import CancelAppointmentView
