from .select_illness import SelectIllnessView
from .view_available_appointments import ViewAvailableAppointment
from .confirm_appointment_selection import ConfirmAppointment
from .create_appointment import CreateAppointment