# Generated by Django 4.0 on 2021-12-12 20:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('doctor_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('patient_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('create_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('begin_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('status', models.CharField(max_length=50)),
                ('duration', models.IntegerField(default=30, validators=[django.core.validators.MaxValueValidator(1440), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness_id', models.IntegerField(default=-1)),
                ('name', models.CharField(default='', max_length=50)),
                ('illness_category', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='IllnessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness_category_id', models.IntegerField(default=-1)),
                ('name', models.CharField(default='', max_length=50)),
                ('illness', models.CharField(default='', max_length=1600)),
                ('specialty_category', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty_id', models.IntegerField(default=-1)),
                ('name', models.CharField(default='', max_length=50)),
                ('specialty_category', models.CharField(default=-1, max_length=1600)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialtyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty_category_id', models.IntegerField(default=-1)),
                ('name', models.CharField(default='', max_length=50)),
                ('illness_category', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('contact', models.CharField(default='', max_length=50)),
                ('bio_gender', models.BooleanField(default=True)),
                ('type', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='health_appointment.user')),
                ('valid_appointment_record', models.CharField(default='', max_length=160000)),
            ],
            bases=('health_appointment.user',),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='health_appointment.user')),
                ('valid_appointment_record', models.CharField(default='', max_length=1600)),
            ],
            bases=('health_appointment.user',),
        ),
    ]
