# Generated by Django 4.0 on 2021-12-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialtycategory',
            name='specialties',
            field=models.CharField(default='', max_length=1600),
        ),
        migrations.AlterField(
            model_name='specialtycategory',
            name='illness_category',
            field=models.CharField(default='', max_length=1600),
        ),
    ]
