# Generated by Django 4.0 on 2021-12-13 07:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('health_appointment', '0003_doctor_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
